gText_Birch_Welcome:: @ texto antes do pokemon
	.string "Entao voce chegou...\n"
	.string "Parabens. Poucos sao capazes disto!\p"
	.string "$"

gText_Birch_Pokemon:: @ texto ao soltar o pokemon (supostamente)
	.string "Vamos ver se é digno de estar aqui.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ Texto apos o pokemon
	.string "Soltei o pokemon :thumbsup:"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
