Text_BootUpPC: @ 827265A
	.string "{PLAYER} ligou o PC.$"

gText_WhichPCShouldBeAccessed:: @ 827266F
	.string "Qual sistema deve ser acessado?$"

gText_AccessedSomeonesPC:: @ 827268C
	.string "Entrou no PC de alguem.$"

gText_StorageSystemOpened:: @ 82726A3
	.string "Sistema de Armazenamento Pokémon aberto.$"

gText_AccessedPlayersPC:: @ 82726C2
	.string "Entrou no PC de {PLAYER}.$"

gText_AccessedLanettesPC:: @ 82726D4
	.string "Entrou no PC de LANETTE.$"
