gText_WouldYouLikeToRestYourPkmn:: @ 82726EB
    .string "Olá, e bem vindo\n"
    .string "ao Centro Pokémon.\p"
    .string "Nós descansamos os seus pokémons\n"
    .string "completamente.\p"
    .string "Gostaria de deixar os seus pokémons?$"

gText_IllTakeYourPkmn:: @ 8272768
    .string "Ok, eu vou pegar os seus pokémons\n"
    .string "por alguns segundos.$"

gText_RestoredPkmnToFullHealth:: @ 8272798
    .string "Obrigada por esperar.\p"
    .string "Restauramos os seus pokémons\n"
    .string "com a vida completa.$"

gText_WeHopeToSeeYouAgain:: @ 82727DB
    .string "Esperamos ver você de novo!$"

gText_WelcomeCutShort:: @ 82727F5 Não vou traduzir o babão agora - Luiz
    .string "Hello, and welcome to\n"
    .string "the POKéMON CENTER.\p"
    .string "We restore your tired POKéMON\n"
    .string "to full health.\p"
    .string "Would you like to…$"

gText_NoticesGoldCard:: @ 8272860 Não vou traduzir o babão agora - Luiz
    .string "Th-that card…\n"
    .string "Could it be… The GOLD CARD?!\p"
    .string "Oh, the gold color is brilliant!\n"
    .string "The four stars seem to sparkle!\p"
    .string "I've seen several TRAINERS with\n"
    .string "a SILVER CARD before, but, {PLAYER},\l"
    .string "you're the first TRAINER I've ever\l"
    .string "seen with a GOLD CARD!\p"
    .string "Okay, {PLAYER}, please allow me\n"
    .string "the honor of resting your POKéMON!$"

gText_YouWantTheUsual:: @ 8272982 Não vou traduzir o babão agora - Luiz
    .string "I'm delighted to see you, {PLAYER}!\n"
    .string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2:: @ 82729C0 
    .string "Ok, eu vou pegar os seus pokémons\n"
    .string "por alguns segundos.$"

gText_ThankYouForWaiting:: @ 82729F0
    .string "Obrigada por esperar.\p"

gText_WeHopeToSeeYouAgain2:: @ 8272A07
    .string "Esperamos ver você de novo!$"
