	.align 2
gText_ConfirmSave:: @ 82C87B4
	.string "Você quer salvar o jogo?$"

gText_AlreadySavedFile:: @ 82C87D5
	.string "Você já tem um progresso salvo\n"
	.string "está ok sobrescrever-lo?$"

gText_SavingDontTurnOff:: @ 82C8810
	.string "SALVANDO…\n"
	.string "NÃO DESLIGUE O JOGO.$"

gText_PlayerSavedGame:: @ 82C8832
	.string "{PLAYER} salvou o jogo.$"

gText_DifferentSaveFile:: @ 82C8845
	.string "AVISO!\p"
	.string "Tem um progreso diferente\n"
	.string "que já foi salvo.\p"
	.string "Se você salvar agora, o arquivo\n"
	.string "da sua outra aventura, incluindo\l"
	.string "seus itens e pokémons serão perdidos.\p"
	.string "Você tem certeza que quer salvar agora\n"
	.string "e sobrescrever o outro progresso?$"

gText_SaveError:: @ 82C892A
	.string "Erro ao salvar.\p"
	.string "Por favor, troque a\n"
	.string "memória de backup.$"

gText_SavingDontTurnOffPower:: @ 82C8959
	.string "SALVANDO…\n"
	.string "NÃO DESLIGUE O JOGO.$"
